logo: # add logo name
title: Ryan Sauge - CV
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/heigvd" # "/bef"the subpath of your site, e.g. /blog
url: "https://rya-sge.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video:  # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: profil.JPG # your photo
author-name: Ryan Sauge #your name
about-author: Edudiant en sécurité informatique à l'HEIG # about author
email:  # your email
phone:  # your pnone number
website: https://rya-sge.github.io/access-denied/ # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link
linkedin_url: https://www.linkedin.com/in/ryan-sauge-045397217/
github_url: https://github.com/rya-sge

# Disqus
discus_identifier:  # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
